jwt:
  header: Authorization
  tokenHead: 'Bearer '

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: h2
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456
  h2:
    console:
      enabled: true
      path: /h2-console